version: '3'
services:
  redis:
    image: redis:6.2.6
    ports:
      - '6379:6379'
  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - '8001:8001'
    volumes:
      - ./redisinsight:/db
      - ./data:/data
